codecov:
  require_ci_to_pass: no

coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
    patch:
      default: false  # disable the patch status that measures patch changes
