name: 'Install msys2'
description: 'Prepares msys2 for Windows builds.'
runs:
  using: composite
  steps:
  - name: Setup msys2
    uses: msys2/setup-msys2@v2
    with:
      path-type: inherit # Important to correctly update PATH

  - name: Prepare env
    shell: 'msys2 {0}'
    env:
      MINGW64_DOWNLOAD_URL: "https://repo.msys2.org/mingw/mingw64"
      MINGW64_DOWNLOAD_FILENAME: "mingw-w64-x86_64-cmake-3.27.7-3-any.pkg.tar.zst"
    run: |
      pacman-key --refresh
      pacman -Sy
      curl -LO "$MINGW64_DOWNLOAD_URL/$MINGW64_DOWNLOAD_FILENAME"
      pacman --noconfirm -U "$MINGW64_DOWNLOAD_FILENAME"
      pacman --noconfirm -S --needed --overwrite \
        base-devel \
        git \
        ninja \
        mingw-w64-x86_64-clang \
        mingw-w64-x86_64-lld \
        mingw-w64-x86_64-rust \
        mingw-w64-x86_64-gcc-libs \
        mingw-w64-x86_64-gcc
      echo "/c/Users/runneradmin/.cargo/bin" >> "${GITHUB_PATH}"
