name: 'Install Solc'
description: 'Installs the Solc compiler.'
inputs:
  solc-default-name:
    description: 'Default name of the solc executable.'
    required: false
    default: 'solc'
  solc-versions:
    description: 'Space-separated list of solc versions to download.'
    required: false
    default: '0.4.26-1.0.1 0.5.17-1.0.1 0.6.12-1.0.1 0.7.6-1.0.1 0.8.26-1.0.1'
  solc-version-latest:
    description: 'Latest version of solc.'
    required: false
    default: '0.8.26-1.0.1'
  output-dir:
    description: 'Output directory for the solc binaries.'
    required: false
    default: 'solc-bins'
runs:
  using: "composite"
  steps:
    - name: Install solc compiler
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        SOLC_URL: "https://github.com/matter-labs/era-solidity/releases/download"
      run: |
        mkdir -p ${{ inputs.output-dir }}
        for SOLC_VERSION in ${{ inputs.solc-versions }}; do
          OUTPUT="${{ inputs.output-dir }}/${{ inputs.solc-default-name }}-${SOLC_VERSION%%-*}"
          case "${RUNNER_OS}-${RUNNER_ARCH}" in
            Linux-ARM64*)
              SOLC_DOWNLOAD_FILENAME="solc-linux-arm64-${SOLC_VERSION}"
              ;;
            Linux-X64*)
              SOLC_DOWNLOAD_FILENAME="solc-linux-amd64-${SOLC_VERSION}"
              ;;
            macOS-ARM64*)
              SOLC_DOWNLOAD_FILENAME="solc-macosx-arm64-${SOLC_VERSION}"
              ;;
            macOS-X64*)
              SOLC_DOWNLOAD_FILENAME="solc-macosx-amd64-${SOLC_VERSION}"
              ;;
            Windows*)
              SOLC_DOWNLOAD_FILENAME="solc-windows-amd64-${SOLC_VERSION}.exe"
              ;;
          esac
          curl --location -o "${OUTPUT}" "${SOLC_URL}/${SOLC_VERSION}/${SOLC_DOWNLOAD_FILENAME}" && \
          chmod a+x "${OUTPUT}"
          [ ${SOLC_VERSION} = ${{ inputs.solc-version-latest }} ] && cp "${OUTPUT}" "${{ inputs.output-dir }}/${{ inputs.solc-default-name }}"
        done
        echo "${PWD}/${{ inputs.output-dir }}" >> "${GITHUB_PATH}"
