[book]
authors = [
    "Oleksandr Zarudnyi",
    "Igor Zhirkov",
    "Anton Baliasnikov",
]
language = "en"
multilingual = false
src = "src"
title = "ZKsync Solidity Compiler Toolchain Documentation"
