name: Check hardhat

on:
  workflow_dispatch:
    inputs:
      zksolc-version:
        description: "Release version of zksolc."
        required: true
        type: string
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-hardhat:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: matter-labs
          repo: zksync-ci-stand
          workflow_file_name: hardhat.yaml
          github_token: ${{ secrets.ZKSYNC_DISPATCH_TOKEN }}
          wait_interval: 30
          client_payload: '{ "zksolc-version": "${{ inputs.zksolc-version || github.ref }}" }'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
