name: Test CLI

on:
  workflow_call:
    inputs:
      name:
        type: string
        default: 'build_linux_amd64'
        required: true
      path:
        type: string
        default: 'releases'
        required: true
      runner:
          type: string
          default: 'matterlabs-ci-runner'
          required: true
      solc_url:
          type: string
          default: 'https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/solc-linux-amd64-v0.8.22+commit.4fc1097e'
          required: true


jobs:
  preparation_and_running_tests:
    runs-on: ${{inputs.runner}}
    permissions:
      contents: read
    strategy:
      matrix:
        test-pattern: [
                "asm.test.ts",
                "common.test.ts",
                "yul.test.ts",
                "zkasm.test.ts"
              ]

    name: '${{ matrix.test-pattern }}'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm packages
        run: |
          cd cli-tests 
          npm ci

      - name: Download '${{ inputs.name }}' artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}

      - if: runner.os == 'Windows'
        name: Download solc for '${{ inputs.name }}'
        run: |
          New-Item -ItemType Directory -Force -Path ${{ inputs.path }}\${{ inputs.name }}
          Invoke-WebRequest -Uri ${{ inputs.solc_url }} -OutFile ${{ inputs.path }}\${{ inputs.name }}\solc.exe
          ls ${{ inputs.path }}\${{ inputs.name }}
        shell: powershell
      
      - if: runner.os == 'Linux' || runner.os == 'macOS'
        name: Download solc for '${{ inputs.name }}'
        run: |
            wget ${{ inputs.solc_url }} -O ${{ inputs.path }}/${{ inputs.name }}/solc
            ls ${{ inputs.path }}/${{ inputs.name }}
      
      - if: runner.os == 'Windows'      
        name: Add File to PATH
        run: |
          echo "$pwd\${{ inputs.path }}\${{ inputs.name }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell

      - if: runner.os == 'Linux' || runner.os == 'macOS'
        name: Change permission and add files to a PATH
        run: |
          chmod +x ./${{ inputs.path }}/${{ inputs.name }}/solc
          chmod +x ./${{ inputs.path }}/${{ inputs.name }}/zksolc
          echo "$(pwd)/${{ inputs.path }}/${{ inputs.name }}" >> $GITHUB_PATH

      - if: runner.os == 'Windows' 
        name: Run tests
        shell: sh
        run: |
          cd cli-tests
          npx jest --verbose --testPathPattern=${{ matrix.test-pattern }}
      
      - if: runner.os == 'Linux' || runner.os == 'macOS'
        name: Run tests
        run: |
          cd cli-tests 
          npx jest --verbose --testPathPattern=${{ matrix.test-pattern }}
